Update: Template Browser Collections Page Category Selection
stikdev/waymark-sdk-tool pull request #30
Opened 2021-07-15 17:53 UTC by jennsun

https://app.clickup.com/t/13qkz2w

Updated layout of the page to have category names listed on the left with two columns of video data on the right instead of an expanded list. Removed aspect ratio filtering so videos of all aspect ratios show up and video thumbnail boxes fit according to respective aspect ratios.

2021-07-16 14:06 UTC, simanthastew requested changes
Nice work! Just a little bit of cleanup :)

2021-07-16 14:06 UTC, simanthastew commented on example_site/src/components/Collections.css
> +  width: 300px;
You should not need to set the width on your grid items! You can use a combination of the [grid column](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column) and gap settings.

[This is a nice code sandbox](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column) to play around with grid layouts to get a better understanding of how all of these work!

2021-07-16 14:06 UTC, simanthastew commented on example_site/src/components/Collections.js
> +    <div>
Do you need this surrounding `div`?

2021-07-16 14:06 UTC, simanthastew commented on example_site/src/components/Collections.js
> +    console.log("Clicked");
Let's get rid of this log statement

2021-07-16 14:06 UTC, simanthastew commented on example_site/src/components/Collections.js
> +        <div>Duration: {template.duration}</div>
Semantically speaking, this should probably be a list! I really liked [this article](https://seekbrevity.com/semantic-markup-important-web-design/) about why respecting HTML semantics is important. 

```
<ul>
    <li>Name: {template.name}</li>
    ....
</ul>
```

Updating that will require some [additional styling](https://www.w3schools.com/css/css_list.asp) to remove the default list styles.

2021-07-16 14:06 UTC, simanthastew commented on example_site/src/components/Collections.js
> +      {shouldShowRefetchWithFilterButton ? (
Are we still using this value and button?

2021-07-16 14:06 UTC, simanthastew commented on example_site/src/components/Collections.js
> +                expand={selectedCollection != null}
I don't think we need to pass down this `expand` prop anymore.

`CollectionTemplates` handles its own loading/error state, and the `expand` value is just used to render the HTML or not, so you could rewrite this like so:
```
{selectedCollection ? (
    <CollectionTemplates .../>
: null)
```

2021-07-16 14:06 UTC, simanthastew commented on example_site/src/components/Collections.js
> +                collection ={collection}
This line and the line below need to be indented one more time

2021-07-19 14:15 UTC, jennsun commented on example_site/src/components/Collections.css
> +  width: 300px;
sandbox: https://codepen.io/discodavey/pen/aJXgbq

2021-07-19 17:20 UTC, simanthastew requested changes
Changes look great! Last thing would be having the selected collection name be blue instead of black so the user knows which collection is selected.

2021-07-19 17:24 UTC, merged